# This workflow generates the reference documentation once per week

name: generate-reference

# Controls when the workflow will run
on:
  # Trigger the workflow on Tuesdays at 2:45pm UTC
  schedule:
    - cron: '45 14 * * 2'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run on GitHub Pages build
  page_build:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "gen-ref"
  gen-reference:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install graphdoc
      - name: Install graphdoc
        run: npm install -g @2fd/graphdoc
        
      # Remove existing folder
      - name: Remove existing reference folder
        run: rm -r $GITHUB_WORKSPACE/report-results/reference
        
      # Generate new documentation
      - name: Run graphdoc to generate new reference documentation
        run: 'graphdoc -e ${{ secrets.REPORT_RESULTS_API_ENDPOINT }} -o ./report-results/reference -x "Authorization: ${{ secrets.REPORT_RESULTS_API_KEY }}"'

      # Create a pull request
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          base: master
          title: '[ACTIONS] Generate reference documentation'
          body: |
            This pull request is automatically generated by GitHub Actions. 
          
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
